# Generated by Django 2.0.3 on 2018-08-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_auto_20180811_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
