# Generated by Django 2.0.3 on 2018-08-13 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_channel_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='topic',
        ),
    ]
