# Generated by Django 2.0.3 on 2018-08-13 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_remove_channel_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subject',
        ),
    ]
